apiVersion: v1
kind: Service
metadata:
  labels:
    service: dotnet-api
  name: dotnet-api
spec:
  ports:
    - name: "5555"
      port: 5555
      targetPort: 80
  selector:
    service: dotnet-api
  type: LoadBalancer
status:
  loadBalancer: {}
  